title: "JOB EDOUARD NKOYOK"
logo: img/nny/jpg
description: "Cybersecurity Cloud Data"
show_downloads: true
theme: jekyll-theme-minimal
lang: en
url: "https://www.yourcustomdomain.com"
baseurl: ""
tagline: "Secure by design — defence, tooling, research"
author:
	name: "Job Edouard Nkoyok"
	email: "nkojoedou@gmail.com"
email: "nkojoedou@gmail.com"
